FROM node:20-alpine

# set the working dir inside container
WORKDIR /app 

# Copy package.json and package-lock.json 
COPY package*.json ./

#Install dependencies
RUN npm install 

# copy all file of project
COPY . . 

#Expose the port 
EXPOSE 5173

# Define the command to run your app
CMD ["npm", "run", "dev"]